// frontend/src/store/instrument/actionTypes.js
export const INSTRUMENT_FETCH_ALL_REQUEST = 'INSTRUMENT_FETCH_ALL_REQUEST';
export const INSTRUMENT_FETCH_ALL_SUCCESS = 'INSTRUMENT_FETCH_ALL_SUCCESS';
export const INSTRUMENT_FETCH_ALL_FAILURE = 'INSTRUMENT_FETCH_ALL_FAILURE';

export const INSTRUMENT_FETCH_ONE_REQUEST = 'INSTRUMENT_FETCH_ONE_REQUEST';
export const INSTRUMENT_FETCH_ONE_SUCCESS = 'INSTRUMENT_FETCH_ONE_SUCCESS';
export const INSTRUMENT_FETCH_ONE_FAILURE = 'INSTRUMENT_FETCH_ONE_FAILURE';

export const INSTRUMENT_ADD_REQUEST = 'INSTRUMENT_ADD_REQUEST';
export const INSTRUMENT_ADD_SUCCESS = 'INSTRUMENT_ADD_SUCCESS';
export const INSTRUMENT_ADD_FAILURE = 'INSTRUMENT_ADD_FAILURE';

export const INSTRUMENT_UPDATE_REQUEST = 'INSTRUMENT_UPDATE_REQUEST';
export const INSTRUMENT_UPDATE_SUCCESS = 'INSTRUMENT_UPDATE_SUCCESS';
export const INSTRUMENT_UPDATE_FAILURE = 'INSTRUMENT_UPDATE_FAILURE';

export const INSTRUMENT_SET_CURRENT_ID = 'INSTRUMENT_SET_CURRENT_ID';