// frontend/src/store/report/actionTypes.js
export const FETCH_REPORT_CONFIG_REQUEST = 'FETCH_REPORT_CONFIG_REQUEST';
export const FETCH_REPORT_CONFIG_SUCCESS = 'FETCH_REPORT_CONFIG_SUCCESS';
export const FETCH_REPORT_CONFIG_FAILURE = 'FETCH_REPORT_CONFIG_FAILURE';

export const UPDATE_REPORT_CONFIG_REQUEST = 'UPDATE_REPORT_CONFIG_REQUEST';
export const UPDATE_REPORT_CONFIG_SUCCESS = 'UPDATE_REPORT_CONFIG_SUCCESS';
export const UPDATE_REPORT_CONFIG_FAILURE = 'UPDATE_REPORT_CONFIG_FAILURE';

export const SET_REPORT_CONFIG_FIELD = 'SET_REPORT_CONFIG_FIELD';