// frontend/src/store/calibration/actionTypes.js
// Generic request states
export const CALIBRATION_REQUEST_PENDING = 'CALIBRATION_REQUEST_PENDING';
export const CALIBRATION_REQUEST_SUCCESS = 'CALIBRATION_REQUEST_SUCCESS';
export const CALIBRATION_REQUEST_FAILURE = 'CALIBRATION_REQUEST_FAILURE';

// Session management
export const CALIBRATION_START_SESSION = 'CALIBRATION_START_SESSION';
export const CALIBRATION_END_SESSION = 'CALIBRATION_END_SESSION';
export const CALIBRATION_SET_SESSION_STATUS = 'CALIBRATION_SET_SESSION_STATUS';

// Instrument and UUT management
export const CALIBRATION_UPDATE_CONNECTED_INSTRUMENTS = 'CALIBRATION_UPDATE_CONNECTED_INSTRUMENTS';
export const CALIBRATION_ADD_UUT_TO_SESSION = 'CALIBRATION_ADD_UUT_TO_SESSION';
export const CALIBRATION_SET_UUT_INPUT_METHOD = 'CALIBRATION_SET_UUT_INPUT_METHOD';

// Test point progression and data
export const CALIBRATION_ADVANCE_TEST_POINT = 'CALIBRATION_ADVANCE_TEST_POINT';
export const CALIBRATION_RETREAT_TEST_POINT = 'CALIBRATION_RETREAT_TEST_POINT';
export const CALIBRATION_UPDATE_TEST_POINT_READING = 'CALIBRATION_UPDATE_TEST_POINT_READING';
export const CALIBRATION_UPDATE_TEST_POINT_STATUS = 'CALIBRATION_UPDATE_TEST_POINT_STATUS';

// Manual interaction prompts
export const CALIBRATION_PROMPT_MANUAL_ACTION = 'CALIBRATION_PROMPT_MANUAL_ACTION';
export const CALIBRATION_DISMISS_MANUAL_ACTION_PROMPT = 'CALIBRATION_DISMISS_MANUAL_ACTION_PROMPT';

// Real-time feedback
export const CALIBRATION_UPDATE_REALTIME_DEVIATION = 'CALIBRATION_UPDATE_REALTIME_DEVIATION';