// frontend/src/store/uncertainty/actionTypes.js
export const FETCH_UNCERTAINTY_FORMULAS_REQUEST = 'FETCH_UNCERTAINTY_FORMULAS_REQUEST';
export const FETCH_UNCERTAINTY_FORMULAS_SUCCESS = 'FETCH_UNCERTAINTY_FORMULAS_SUCCESS';
export const FETCH_UNCERTAINTY_FORMULAS_FAILURE = 'FETCH_UNCERTAINTY_FORMULAS_FAILURE';

export const SAVE_UNCERTAINTY_FORMULA_REQUEST = 'SAVE_UNCERTAINTY_FORMULA_REQUEST';
export const SAVE_UNCERTAINTY_FORMULA_SUCCESS = 'SAVE_UNCERTAINTY_FORMULA_SUCCESS';
export const SAVE_UNCERTAINTY_FORMULA_FAILURE = 'SAVE_UNCERTAINTY_FORMULA_FAILURE';

export const TEST_UNCERTAINTY_FORMULA_REQUEST = 'TEST_UNCERTAINTY_FORMULA_REQUEST';
export const TEST_UNCERTAINTY_FORMULA_SUCCESS = 'TEST_UNCERTAINTY_FORMULA_SUCCESS';
export const TEST_UNCERTAINTY_FORMULA_FAILURE = 'TEST_UNCERTAINTY_FORMULA_FAILURE';

export const RESTORE_UNCERTAINTY_FORMULA_REQUEST = 'RESTORE_UNCERTAINTY_FORMULA_REQUEST';
export const RESTORE_UNCERTAINTY_FORMULA_SUCCESS = 'RESTORE_UNCERTAINTY_FORMULA_SUCCESS';
export const RESTORE_UNCERTAINTY_FORMULA_FAILURE = 'RESTORE_UNCERTAINTY_FORMULA_FAILURE';

export const SET_CURRENT_EDITING_FORMULA = 'SET_CURRENT_EDITING_FORMULA';
export const UPDATE_CURRENT_EDITING_FORMULA = 'UPDATE_CURRENT_EDITING_FORMULA';
export const CLEAR_CURRENT_EDITING_FORMULA = 'CLEAR_CURRENT_EDITING_FORMULA';