// frontend/src/store/template/actionTypes.js
export const FETCH_TEMPLATES_REQUEST = 'template/FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS = 'template/FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE = 'template/FETCH_TEMPLATES_FAILURE';

export const FETCH_TEMPLATE_BY_ID_REQUEST = 'template/FETCH_TEMPLATE_BY_ID_REQUEST';
export const FETCH_TEMPLATE_BY_ID_SUCCESS = 'template/FETCH_TEMPLATE_BY_ID_SUCCESS';
export const FETCH_TEMPLATE_BY_ID_FAILURE = 'template/FETCH_TEMPLATE_BY_ID_FAILURE';

export const SET_SELECTED_TEMPLATE_ID = 'template/SET_SELECTED_TEMPLATE_ID';