// frontend/src/store/admin/actionTypes.js
export const FETCH_VALIDATION_RULES_REQUEST = 'admin/FETCH_VALIDATION_RULES_REQUEST';
export const FETCH_VALIDATION_RULES_SUCCESS = 'admin/FETCH_VALIDATION_RULES_SUCCESS';
export const FETCH_VALIDATION_RULES_FAILURE = 'admin/FETCH_VALIDATION_RULES_FAILURE';
export const SELECT_VALIDATION_RULE = 'admin/SELECT_VALIDATION_RULE';
export const CLEAR_SELECTED_VALIDATION_RULE = 'admin/CLEAR_SELECTED_VALIDATION_RULE';