// frontend/src/store/uncertaintyFormula/actionTypes.js
// Action Types for UncertaintyFormula module

// Fetching formulas
export const FETCH_UNCERTAINTY_FORMULAS_REQUEST = 'FETCH_UNCERTAINTY_FORMULAS_REQUEST';
export const FETCH_UNCERTAINTY_FORMULAS_SUCCESS = 'FETCH_UNCERTAINTY_FORMULAS_SUCCESS';
export const FETCH_UNCERTAINTY_FORMULAS_FAILURE = 'FETCH_UNCERTAINTY_FORMULAS_FAILURE';

export const FETCH_UNCERTAINTY_FORMULA_BY_ID_REQUEST = 'FETCH_UNCERTAINTY_FORMULA_BY_ID_REQUEST';
export const FETCH_UNCERTAINTY_FORMULA_BY_ID_SUCCESS = 'FETCH_UNCERTAINTY_FORMULA_BY_ID_SUCCESS';
export const FETCH_UNCERTAINTY_FORMULA_BY_ID_FAILURE = 'FETCH_UNCERTAINTY_FORMULA_BY_ID_FAILURE';

// Creating a new formula
export const CREATE_UNCERTAINTY_FORMULA_REQUEST = 'CREATE_UNCERTAINTY_FORMULA_REQUEST';
export const CREATE_UNCERTAINTY_FORMULA_SUCCESS = 'CREATE_UNCERTAINTY_FORMULA_SUCCESS';
export const CREATE_UNCERTAINTY_FORMULA_FAILURE = 'CREATE_UNCERTAINTY_FORMULA_FAILURE';

// Updating an existing formula
export const UPDATE_UNCERTAINTY_FORMULA_REQUEST = 'UPDATE_UNCERTAINTY_FORMULA_REQUEST';
export const UPDATE_UNCERTAINTY_FORMULA_SUCCESS = 'UPDATE_UNCERTAINTY_FORMULA_SUCCESS';
export const UPDATE_UNCERTAINTY_FORMULA_FAILURE = 'UPDATE_UNCERTAINTY_FORMULA_FAILURE';

// Deleting a formula
export const DELETE_UNCERTAINTY_FORMULA_REQUEST = 'DELETE_UNCERTAINTY_FORMULA_REQUEST';
export const DELETE_UNCERTAINTY_FORMULA_SUCCESS = 'DELETE_UNCERTAINTY_FORMULA_SUCCESS';
export const DELETE_UNCERTAINTY_FORMULA_FAILURE = 'DELETE_UNCERTAINTY_FORMULA_FAILURE';

// Testing a formula with sample data (US-016, US-019, US-045)
export const TEST_UNCERTAINTY_FORMULA_REQUEST = 'TEST_UNCERTAINTY_FORMULA_REQUEST';
export const TEST_UNCERTAINTY_FORMULA_SUCCESS = 'TEST_UNCERTAINTY_FORMULA_SUCCESS';
export const TEST_UNCERTAINTY_FORMULA_FAILURE = 'TEST_UNCERTAINTY_FORMULA_FAILURE';
export const CLEAR_TEST_RESULTS = 'CLEAR_TEST_RESULTS';

// Restoring a formula to default (US-020)
export const RESTORE_UNCERTAINTY_FORMULA_DEFAULT_REQUEST = 'RESTORE_UNCERTAINTY_FORMULA_DEFAULT_REQUEST';
export const RESTORE_UNCERTAINTY_FORMULA_DEFAULT_SUCCESS = 'RESTORE_UNCERTAINTY_FORMULA_DEFAULT_SUCCESS';
export const RESTORE_UNCERTAINTY_FORMULA_DEFAULT_FAILURE = 'RESTORE_UNCERTAINTY_FORMULA_DEFAULT_FAILURE';

// Setting the currently active formula in the editor
export const SET_ACTIVE_UNCERTAINTY_FORMULA = 'SET_ACTIVE_UNCERTAINTY_FORMULA';